import type { GameState } from "@/lib/game/types";

const BASE_GAME_STATE: Omit<GameState, "updatedAt"> = {
  gameId: "RR-02162",
  round: 1,
  phase: "programming",
  currentPlayerId: "player-1",
  board: {
    width: 10,
    height: 10,
    elements: [
      { id: "wall-1", type: "wall", x: 2, z: 2, side: "east" },
      { id: "wall-2", type: "wall", x: 6, z: 5, side: "north" },
      { id: "wall-3", type: "wall", x: 7, z: 7, side: "west" },
      { id: "checkpoint-1", type: "checkpoint", x: 8, z: 1, order: 1 },
      { id: "checkpoint-2", type: "checkpoint", x: 1, z: 8, order: 2 },
      { id: "pit-1", type: "pit", x: 4, z: 4 },
      { id: "pit-2", type: "pit", x: 5, z: 4 },
      {
        id: "conveyor-1",
        type: "conveyor",
        x: 3,
        z: 6,
        direction: "east",
      },
      {
        id: "conveyor-2",
        type: "conveyor",
        x: 4,
        z: 6,
        direction: "east",
      },
      {
        id: "gear-1",
        type: "gear",
        x: 7,
        z: 3,
        rotation: "clockwise",
      },
    ],
  },
  robots: [
    {
      id: "robot-1",
      playerId: "player-1",
      name: "Bolt",
      color: "#ff625a",
      x: 1,
      z: 8,
      direction: "north",
    },
    {
      id: "robot-2",
      playerId: "player-2",
      name: "Vector",
      color: "#4dd8ff",
      x: 3,
      z: 8,
      direction: "north",
    },
    {
      id: "robot-3",
      playerId: "player-3",
      name: "Rivet",
      color: "#ffc857",
      x: 6,
      z: 8,
      direction: "north",
    },
    {
      id: "robot-4",
      playerId: "player-4",
      name: "Pixel",
      color: "#a78bfa",
      x: 8,
      z: 8,
      direction: "north",
    },
  ],
  players: [
    {
      id: "player-1",
      name: "You",
      robotId: "robot-1",
      damage: 0,
      lives: 3,
      checkpointsReached: 0,
      programmedCardCount: 0,
      connected: true,
    },
    {
      id: "player-2",
      name: "Maya",
      robotId: "robot-2",
      damage: 0,
      lives: 3,
      checkpointsReached: 0,
      programmedCardCount: 3,
      connected: true,
    },
    {
      id: "player-3",
      name: "Jonas",
      robotId: "robot-3",
      damage: 0,
      lives: 3,
      checkpointsReached: 0,
      programmedCardCount: 5,
      connected: true,
    },
    {
      id: "player-4",
      name: "Freja",
      robotId: "robot-4",
      damage: 0,
      lives: 3,
      checkpointsReached: 0,
      programmedCardCount: 2,
      connected: false,
    },
  ],
  availableCards: [
    { id: "card-1", name: "Move 3", type: "move", value: 3, priority: 840 },
    { id: "card-2", name: "Move 2", type: "move", value: 2, priority: 670 },
    { id: "card-3", name: "Move 1", type: "move", value: 1, priority: 510 },
    {
      id: "card-4",
      name: "Rotate left",
      type: "rotate",
      value: -1,
      priority: 330,
    },
    {
      id: "card-5",
      name: "Rotate right",
      type: "rotate",
      value: 1,
      priority: 260,
    },
    { id: "card-6", name: "Back up", type: "backup", value: -1, priority: 80 },
  ],
};

export function getMockGameState(): GameState {
  return {
    ...BASE_GAME_STATE,
    board: {
      ...BASE_GAME_STATE.board,
      elements: BASE_GAME_STATE.board.elements.map((element) => ({
        ...element,
      })),
    },
    robots: BASE_GAME_STATE.robots.map((robot) => ({ ...robot })),
    players: BASE_GAME_STATE.players.map((player) => ({ ...player })),
    availableCards: BASE_GAME_STATE.availableCards.map((card) => ({ ...card })),
    updatedAt: new Date().toISOString(),
  };
}
